export const GLOBAL_ERRORS = "GLOBAL_ERRORS";
export const GLOBAL_SUCCESS = "GLOBAL_SUCCESS";
export const CUSTOM_SUCCESS = "CUSTOM_SUCCESS";
export const GLOBAL_LOADING = "GLOBAL_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ACTIVATION_REQUIRED = "ACTIVATION_REQUIRED";
